variables:
  CD_REGISTRY_IMAGE: "auwardoctor/email-newsletter"

stages:
  - build_app
  - test
  - build_image

before_script:
  - docker login -u "auwardoctor"

default:
  image: rust:slim 

build_app:
  stage: build_app
  before_script:
    - apt update -qq && apt install -y -qq pkg-config && apt install -y -qq openssl
    - apt install -y -qq libssl-dev
  script: 
    - echo "Beginning build. . ."
    - cargo build --release
  tags:
    - hpt730

test:
  stage: test
  needs: [build_app]
  before_script:
    - apt update -qq && apt install -y -qq pkg-config && apt install -y -qq openssl
    - apt install -y -qq libssl-dev
  script:
    - echo "Beginning test. . ."
    - cargo test
  tags:
    - hpt730

build_image:
  stage: build_image
  image: docker
  needs: [build_app]
  script:
    - docker pull $CD_REGISTRY_IMAGE:latest || true
    - docker build --tag $CD_REGISTRY_IMAGE:latest --file Dockerfile .
  tags:
    - hpt730




