stages:
  - build

default:
  image: rust:slim 

build:
  stage: build
  before_script:
    - apt update -qq && apt install -y -qq pkg-config
  script: 
    - echo "Beginning build. . ."
    - cargo build
  tags:
    - hpt730
