variables:
  CD_REGISTRY_IMAGE: "auwardoctor/email-newsletter"

stages:
  - build_app
  - test
  - build_image

default:
  image: rust:slim 

build_app:
  stage: build_app
  before_script:
    - apt update -qq && apt install -y -qq pkg-config && apt install -y -qq openssl
    - apt install -y -qq libssl-dev
  script: 
    - echo "Beginning build. . ."
    - cargo build
  tags:
    - hpt730

test:
  stage: test
  before_script:
    - apt update -qq && apt install -y -qq pkg-config && apt install -y -qq openssl
    - apt install -y -qq libssl-dev
  script:
    - echo "Beginning test. . ."
    - cargo test
  tags:
    - hpt730

build_image:
  stage: build_image
  needs: [build_app test]
  script:
    - docker pull $CD_REGISTRY_IMAGE:latest || true
    - docker build --tag $CD_REGISTRY_IMAGE:latest --file Dockerfile .



