[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-rt = "2.10.0"
reqwest = "0.12.7"
tokio = "1.40.0"

[lib]
path = "src/lib.rs"
name = "zero2prod"